### PR TITLE
feat: add How It Works and Get Assistance pages

### PR DESCRIPTION
**Pull request by jaredcwhite**
Addresses issue #449 

Preview new content here: https://deploy-preview-459--hopeful-rosalind-ded1cd.netlify.app
(FYI, the Sign Up homepage action block isn't enabled for SJ currently…not part of this issue.)

## Deploy Notes

**Important!** Two ENV vars will need to change when this gets rolled out:

* `SHOW_HIW` = `TRUE`
* `HOUSING_COUNSELOR_SERVICE_URL` = `/get-assistance`

### CODE REVIEW

**Review by ColinBuyck — CHANGES_REQUESTED** [review]
One thing I noticed was that the subtitle on the Get Assistance page is missing translations. 
image

**Comment by ColinBuyck** [comment]
@jaredcwhite I also noticed some changes to the linking in the copy that don't seem to be reflected in the PR changes. Particularly around the "Tables for San José" and "Resources" Page referenced in the screenshot. I feel a little unclear on what it is suggesting and may need some confirmation from @kathyccheng on the exact desired linking.
Screen Shot 2022-08-15 at 11 20 55 AM
Screen Shot 2022-08-15 at 11 21 08 AM

**Comment by jaredcwhite** [comment]
@ColinBuyck Yeah let's see if we can merge this through, if it's just the question about the links. I'm pretty sure we don't want the entire title text of the HTML page on each link.

**Comment by ColinBuyck** [comment]
> One thing I noticed was that the subtitle on the Get Assistance page is missing translations. image

Beyond the linking, there's just this one change!

**Review by ColinBuyck — APPROVED** [review]
LGTM!

**Comment by jaredcwhite** [comment]
anyone care to second the motion? 😄

**Review by YazeedLoonat — APPROVED** [review]
LGTM

**Pull request merged**
