### PR TITLE
Latest QA updates to Skylyne

### PR DESCRIPTION
**Pull request by jaredcwhite**

### CODE REVIEW

**Comment by jaredcwhite** [comment]
Review App: https://5ec59a27de6abe0007f92f81--wonderful-joliot-c00737.netlify.app/listing/q3h9p31e/the_skylyne_at_temescal_3883_turquoise_way_oakland_ca

**Comment by jaredcwhite** [comment]
Updated waitlist size to 26, added Due at Interview to Required Documents:
https://5ec6ddd4aa7c140007437544--wonderful-joliot-c00737.netlify.app/listing/q3h9p31e/the_skylyne_at_temescal_3883_turquoise_way_oakland_ca

**Comment by jaredcwhite** [comment]
New Mapbox zoom level:
https://5ec6ebf88f89c700075f2aef--wonderful-joliot-c00737.netlify.app/listing/q3h9p31e/the_skylyne_at_temescal_3883_turquoise_way_oakland_ca

**Comment by jaredcwhite** [comment]
Few more changes requested by Oakland:
https://5ec83ff1b486ce000692fc06--wonderful-joliot-c00737.netlify.app/listing/q3h9p31e/the_skylyne_at_temescal_3883_turquoise_way_oakland_ca

**Comment by bk3c** [comment]
My only concern with this is that we seem to be editing the TCAC 2019 amounts, so I just want to make sure that those are actually retroactively changing (or were otherwise wrong to begin with) and it's not a 2020 update. If it's the latter, I'd like to have a new 2020 chart so that we can have the history and not overwrite it

**Comment by jaredcwhite** [comment]
> My only concern with this is that we seem to be editing the TCAC 2019 amounts

@bk3c Good point, I don't know where those exact numbers are being sourced from. Question for Vu-Bang?

**Comment by bk3c** [comment]
Yeah, I asked him in a meeting earlier today, and he was going to look into it and get back to us.

**Comment by vubang228** [comment]
@jaredcwhite They wanted to extend this deadline from today to June 22, 2020 at 5PM. Can you update the listing so it stays up? Thanks! @bk3c

**Comment by bk3c** [comment]
Note the comment above is addressed in #72

**Pull request merged**
