### PR TITLE
Update core to 0.1.0

### PR DESCRIPTION
**Pull request by bk3c**
This was an exceedingly difficult merge, so I'd love to get as many eyes as possible to make sure I didn't create problems.

### CODE REVIEW

**Comment by bk3c** [comment]
Note that there are still a significant number of places where the jurisdiction apps need to be updated to match current reference, but I'm splitting that off into #52 in the hopes of getting this reviewed and merged before it gets any bigger or more difficult to review.

**Comment by jaredcwhite** [comment]
@bk3c I'll give this a spin locally and see if I notice anything off.

**Comment by jaredcwhite** [comment]
@bk3c One implementation issue I see is the "See Details" button has the extra slug at the end of the URL, but the image card doesn't. An issue somewhere down in the ListingsList component though, so that would have to get fixed in the ui-components package.

**Comment by jaredcwhite** [comment]
Actually it does an automatic redirect when the slug's missing, so this probably isn't a showstopper.

**Pull request merged**
