### PR TITLE
Add Alameda override translations and Adjust view resource language

### PR DESCRIPTION
**Pull request by netrabadami**
Pull Request includes 
1. Issue #188 Alameda Translations Override
2. Issue #199 Adjust View Language

Used Alameda Specific .json and AdditionalResources.mdx and AdditionalResourcesSidebar.mdx

### CODE REVIEW

**Comment by jaredcwhite** [comment]
PR looks good! LGTM :+1:

**Review by jaredcwhite — APPROVED** [review]

**Comment by netrabadami** [comment]
@jaredcwhite Thank you for your review. I am concerned about the build failure, is it something to worry?

**Comment by software-project** [comment]
@netrabadami I spoke with @pbn4. The base for this PR should be 0.3-alameda. So I think you need to manually move those changes there (basing on the new 0.3 branch). Code structure is complete different so changing the target of this PR is not going to make a cut.

**Comment by netrabadami** [comment]
@software-project Thanks for the update. Where is the code for 0.3-alameda? can I have the link/access so that I can place my changes on it.

**Comment by jaredcwhite** [comment]
Closing this since we've merged in #212

**Pull request closed without merging**
