### PR TITLE
release: update of Seeds toast and icon

### PR DESCRIPTION
**Pull request by jaredcwhite**
Includes these PRs from Core:

* https://github.com/bloom-housing/bloom/pull/3962
* https://github.com/bloom-housing/bloom/pull/3956
* https://github.com/bloom-housing/bloom/pull/3993
* https://github.com/bloom-housing/bloom/pull/4038

### CODE REVIEW

**Comment by jaredcwhite** [comment]
FYI, the test failure in `cypress-partners` is another issue which came in from `main`, it's not caused by this PR.

**Comment by emilyjablonski** [comment]
Sorry I know this was opened a while ago, curious if you remember any significant changes bringing this over from core?

**Comment by jaredcwhite** [comment]
@emilyjablonski Yeah, there were some icons which needed updating in Markdown content, like Get Assistance I believe. You could look through the commit history for the PR to see which changes were made after the initial chery picks.

**Comment by ColinBuyck** [comment]
Flagging that there's some merge conflicts to resolve here!

**Comment by jaredcwhite** [comment]
Note: want to get this PR merged in before adding the PR for Dialog/Drawer uptake.

**Review by emilyjablonski — APPROVED** [review]

**Pull request merged**
