### PR TITLE
fix/update error string to not include log-in text

### PR DESCRIPTION
**Pull request by emilyjablonski**
https://app.zenhub.com/workspaces/bloom-5dc32d7144bd400001315dac/issues/bloom-housing/bloom/1027

Not sure if this is okay with however we are doing translations :)

### CODE REVIEW

**Comment by jaredcwhite** [comment]
@emilyjablonski Ah, so everything in `ui-components` is "off-limits" for updates to housingbayarea because we load in the published NPM module from upstream. Instead, you'd want to change one of the override translation files in `sites/public/page_content/locale_overrides`. Let me know if you need any more context on how that all works.

**Review by jaredcwhite — CHANGES_REQUESTED** [review]
(forgot to comment in the review)

**Comment by emilyjablonski** [comment]
@jaredcwhite

**Comment by emilyjablonski** [comment]
@jaredcwhite

**Comment by jaredcwhite** [comment]
@emilyjablonski sorry for the wait! merging

**Pull request merged**
