### PR TITLE
Update triton info and SMC QA items

### LINKED ISSUE #47: Adjust the AMI data and deadline for Triton
The Application Deadline for the Triton should really now be May 27, 2020 at 5:00 PM, and the revised AMI data is:

## Qualifying Income Levels

HOUSEHOLD SIZE | 1 | 2 | 3 | 4 | 5 | 6 | 7
-- | -- | -- | -- | -- | -- | -- | --
Very Low Income (50%) | $60,900 | $69,600 | $78,300 | $87,000 | $94,000 | $100,950 | $107,900
Low Income (80%) | $97,600 | $111,550 | $125,500 | $139,400 | $150,600 | $161,750 | $172,900
Moderate Income (120%) | $120,200 | $137,350 | $154,550 | $171,700 | $185,450 | $199,150 | $212,900

## Very Low Income (50%) Renters

BEDROOMS | Jr. 1 | 1 | 2 | 3
-- | -- | -- | -- | --
Very Low Income (50%) Renters | $1,369 | $1,575 | $1,756 | $1,930

## Low Income (80%) Renters

BEDROOMS | Jr. 1 | 1 | 2 | 3
-- | -- | -- | -- | --
Low Income (80%) Renters | $2,286 | $2,624 | $2,936 | $3,240

## Moderate Income (120%) Renters

BEDROOMS | Jr. 1 | 1 | 2 | 3
-- | -- | -- | -- | --
Moderate Income (120%) Renters | $2,600 | $2,984 | $3,340 | $3,690

### PR DESCRIPTION
**Pull request by bk3c**
Fixes #47 when it's done.

I'll leave the AMI charts for @software-project or whoever gets to it, but I wanted to at least get the date updated so it wasn't visually so wrong on the Browse Listings page.

I also updated the site name in the header and moved up to the latest Bloom core packages. There are probably still some other strings to do.

### CODE REVIEW

**Comment by software-project** [comment]
@bk3c AMI should be good now

**Comment by bk3c** [comment]
@software-project can you resolve the merge conflicts when you have a moment?

**Comment by software-project** [comment]
@bk3c updated

**Comment by bk3c** [comment]
Ok, this looks generally good to me, pending a weird extra band of pixels in the footer, and a definite need to triple check all of the data elements. Merging so we can see the front and back end working correctly on staging.

**Pull request merged**
