### PR TITLE
SMC and SJ Listings Final QA

### PR DESCRIPTION
**Pull request by jacchau**
-Update application due date to 3/13/20, 3:00pm pst

### CODE REVIEW

**Comment by jacchau** [comment]
@software-project added some minor changes for Gish and Archer. In the listings the '  "disableUnitsAccordion": true,' is set to true, however when I am QA'ing it in https://sj.bloom.exygy.dev/, the units feature accordion is still expandable. Can you look into that?

**Comment by jacchau** [comment]
I added the county as "San Mateo" to the building address for Brunswick and Bounty Drive listings @software-project hopefully this fixes the problem of the listings not showing up for SMC in smc.bloom.exygy.dev? I think county is the key used to determine which public app the listing is deployed right @jaredcwhite ?

**Comment by bk3c** [comment]
Per my comment in slack I think the listing IDs need to be fixed to be proper nanoids, but other than that this looks good. If you want to do a separate PR for the IDs across SJ and SMC just let me know and I can merge this one first.

**Comment by jacchau** [comment]
Thanks @bk3c , @software-project  - can you update the listing id's so that they are nanonids early next week? Unfortunately, I am not sure what the steps are to generate the nanoids as I have not done it before for the listing and unit ids. FYI i've added a commit to Triton listing so that the floor is an empty string so that the unit accordion doesn't show incorrect floor details. (Triton has declined to provide us and the public with the floor information). 

When the staging sites are deployed, please QA the units accordion for each of the listings - I set the 'disableunitsaccordion' as true for Brunswick, Triton, MetNorth, and Gish - the units accordion should not be expandable by the user

**Pull request merged**
