### PR TITLE
393/how it works translations

### PR DESCRIPTION
**Pull request by jaredcwhite**
Addresses issue #393 (partially). Also dependent on upstream merge of bloom-housing/bloom#2734 before then implementing #394.

Filipino support will be implemented in a separate PR.

### CODE REVIEW

**Comment by emilyjablonski** [comment]
@jaredcwhite I'm not seeing the `how it works` portion on the homepage, maybe I am missing some piece of necessary setup?

**Comment by kathyccheng** [comment]
@emilyjablonski Sean added an env variable for it!

**Comment by emilyjablonski** [comment]
@kathyccheng Yeah I have that set to true, but not seeing the content on the homepage

**Comment by jaredcwhite** [comment]
@emilyjablonski Seems to be case sensitive string…so `TRUE` works but `true` actually doesn't

**Review by seanmalbert — APPROVED** [review]
lgtm

**Pull request merged**
