### PR TITLE
Extend the Skylyne application deadline to 6/22/20

### PR DESCRIPTION
**Pull request by bk3c**
Minimal JSON change to extend their deadline per request.

### CODE REVIEW

**Comment by bk3c** [comment]
Merging on self-QA; we'll double-check on master.

**Comment by vubang228** [comment]
@bk3c they'd like to bring this listing back online, i'm pushing them to give us a deadline for the application, as I recall we needed to have a deadline to post. Is it possible to leave up until they want it pulled it down (when they reach 500 applicants, they're at 217).

**Comment by vubang228** [comment]
@bk3c we confirmed a final application due date: 10/1/2020 at 5PM. Can we bring this back live with the new due date? 

I updated the spreadsheet: https://docs.google.com/spreadsheets/d/1KoWC9fb9hKoBuwUCZ80rod4qcjbT70l4dO1y2Lr0szg/edit?usp=sharing

**Comment by vubang228** [comment]
Also updated the spreadsheet with the final waitlist size and current waitlist size

**Pull request merged**
