### PR TITLE
Add initial version of Reilly Station listing

### PR DESCRIPTION
**Pull request by pbn4**
Closes https://github.com/housingbayarea/bloom/issues/97

### CODE REVIEW

**Comment by pbn4** [comment]
@bk3c Do we have Alameda HUD2019 and HUD2020 AMI data?

**Comment by vubang228** [comment]
@pbn4 we can use the AMI chart that they pasted into Line 85 of the spreadsheet

**Comment by bk3c** [comment]
Pairing with @kathyccheng to do QA on this listing so I'm sure she'll have more comments, but one thing I'm seeing is that the availability table at the top is showing WAITLIST instead of the number of available units:

image

**Comment by kathyccheng** [comment]
Application Due Date should be 4pm instead of 11pm on 8/21/20
image

**Comment by kathyccheng** [comment]
I think max deposit should be $2,036 not $2.036
image

**Comment by kathyccheng** [comment]
All common areas are wheelchair **accessible**. 50% of the units are built out for persons with mobility disabilities with all units that can **easily** be adapted.
Typo: accessable --> accessible, eaisly --> easily 

image

**Comment by kathyccheng** [comment]
Is it possible for these to be in bullet points? 
image

**Comment by kathyccheng** [comment]
@bk3c is they didn't provide a link since it's optional, should we show this?
image

**Comment by kathyccheng** [comment]
Apply Online currently takes you back to the listing page, but looks like it should link to: https://www.on-site.com/apply/property/341392

image

**Comment by kathyccheng** [comment]
Typo: seperate should be separate 

image

**Comment by pbn4** [comment]
@bk3c @kathyccheng The developer defined square footage as "Starting at 845" and initially I simplified it to 845, maybe we should change that to 845+ or something else reflecting the actual state?

**Comment by kathyccheng** [comment]
@pbn4 @bk3c my instinct is it's probably okay to keep the simplified for now and we can see if they pick up on it and ask us to update later, but @bk3c might have more context for how requests like this have played out in the past and it's better to get ahead of it now

**Comment by kathyccheng** [comment]
@pbn4 took another look and most of the issues I found last night are looking good! But I noticed that the unit types seem to have switched to studio, 1 br, 2 br instead of 1br, 2br, 3br 

image

**Comment by vubang228** [comment]
Generally, folks have gone with the simplified lower SF number when they don't want to be specific about the range, so we can start with just 845 and see what they say. @kathyccheng @bk3c @pbn4

**Comment by vubang228** [comment]
@kathyccheng @bk3c @pbn4 I just got more clarity from Eden Housing on a few items we discussed today: 

1. We can use 3000 for the waitlist (Sorry @slowbot, hoping this number is ok) 
2. We can use the updated Alameda County LIHTC MTSP income limits, see below. 
3. Including the language for converting the waitlist over to Canyon Flats is ok 

Screen Shot 2020-07-28 at 4 35 54 PM

**Comment by vubang228** [comment]
@bk3c @pbn4 City of Fremont found some errors in the preference section. I updated the spreadsheet listing with the updated language: https://docs.google.com/spreadsheets/d/1WU0aDSfFrisIY9E7CBqT29OG8lpqbWTYD4IBH6OrpIg/edit?usp=sharing 

Thanks! @kathyccheng

**Pull request merged**
