### PR TITLE
Add Montara listing

### PR DESCRIPTION
**Pull request by pbn4**
Closes https://github.com/housingbayarea/bloom/issues/65

### CODE REVIEW

**Comment by bk3c** [comment]
We're having some build system issues where this isn't on a publicly viewable environment yet, but @slowbot can you take a look at the first draft locally?

Things I noticed on my quick pass:

- Deadline is at midnight, do we want that?
- Is the 400 waitlist slots right? Do we want to show the 0 current like that?
- No phone number for the leasing agent yet
- AMI table is blank (known issue which I believe @antonelitum is working on with @vubang228)
- Additional fees section has weird one decimal notation, should be two or zero

**Comment by bk3c** [comment]
Also, fwiw, we landed the code that allows Markdown in text fields upstream, so there's now the option to add carriage returns, bullets, etc. in the longer fields where appropriate. Still a little work to do to integrate that with the SMC site, but we should be able to do it this week if that would make a meaningful difference here.

**Comment by vubang228** [comment]
@bk3c I think @antonelitum and I provided the AMI table we need to get this filled out: https://housing.smcgov.org/sites/housing.smcgov.org/files/2020%20Income%20Limits%20revised%2004282020.pdf

Let me know if we need anything else? The rest we can update in the next pass, that AMI table we'll need for BRIDGE to review however.

**Comment by pbn4** [comment]
@bk3c I added the AMI table for san mateo county 2020 TCAC. Units in spreadsheet use 60% ami percentage which is not defined in the provided table. For the time being I updated the branch with an existing but incorrect 80% value.

**Comment by pbn4** [comment]
> Additional fees section has weird one decimal notation, should be two or zero

Fixed

**Pull request merged**
