### PR TITLE
Add atlas listing

### LINKED ISSUE #108: Create Alameda Atlas Listing - Developer: Greystar
This is the listing spreadsheet https://docs.google.com/spreadsheets/d/1kaEN635Vu1WVHQe0sLVnPh8laaOloZElu5Ki46m0U4k/edit#gid=1787912937

Expected Launch Date: Sept 8, 2020

### PR DESCRIPTION
**Pull request by software-project**
Resolves #108

### CODE REVIEW

**Comment by kathyccheng** [comment]
@software-project new image has been added!
atlas op1 (1)

**Comment by kathyccheng** [comment]
@software-project let me know if you need anything else here to merge in for QA!

**Comment by software-project** [comment]
@bk3c @kathyccheng bg image added. This one is ready for QA as well.

**Review by bk3c — APPROVED** [review]
merging for QA on staging

**Pull request merged**
