### PR TITLE
feat: emeryville ami chart

### PR DESCRIPTION
**Pull request by YazeedLoonat**
creates ami chart for emeryville in Alameda

issue: https://github.com/bloom-housing/bloom/issues/3707

### CODE REVIEW

**Comment by ColinBuyck** [comment]
Do you mind filling out the template and creating and/or linking the issue @YazeedLoonat?

**Review by ColinBuyck — COMMENTED** [review]
The values look good to me but I think we should get input on the ami-chart naming since it currently stands out from the others imo @sarahlazarich 
Screenshot 2023-11-13 at 11 14 11 AM

**Comment by sarahlazarich** [comment]
Can we call the AMI chart to read "Emeryville 2023" ?

**Comment by YazeedLoonat** [comment]
Hey @ColinBuyck got this updated for ya!

**Review by ColinBuyck — APPROVED** [review]
LGTM 🍕

**Pull request merged**
