### PR TITLE
feat: move jurisdiction specific features to main

### PR DESCRIPTION
**Pull request by ludtkemorgan**
# Pull Request Template

## Issue Overview

This PR addresses #3117

- [ ] This change addresses the issue in full
- [x] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

This is a drastic change in how the jurisdictions branching code is done. Hopefully this will make it more streamline when adding a new feature and/or updating a feature that is just for one jurisdiction. Theoretically it will help prevent rework in each jurisdiction, reduction of time spent on PRs, prevent unintended divergences in the different branches, and speed up the release time.

The main changes are the following:
1. No more need for the jurisdiction specific branches. All of the unique code for each jurisdiction is in its corresponding override directory.
2. Translations for each jurisdiction are pulled in in the following order. Each step overrides the previous if the same translation key exists.
     1. Pull in english translations from base app (ones from core)
     2. Pull in locale translations from base app
     3. Pull in english translations from bay-area overrides
     4. Pull in locale translations from bay-area overrides
     5. Pull in english Jurisdiction overrides
     6. Pull in locale Jurisdiction overrides
3. Pages where the content is different per jurisdiction there is branching logic in that page that is dynamically imported. For example the How It Works page is the same base file for every jurisdiction with the same Header and css overrides. However for the content of the page the `pageContent` is now imported dynamically based on the jurisdiction.
    - The home page is a slight divergence to this as the dynamic importing doesn't work as cleanly. In that case there is if statements to determine the page content of the footer and feedback link.
4. If there is ever going to be a feature that is only for one jurisdiction or we would want to potentially release them at different time we will need to add a feature flag. That logic would be the same way we have been doing it already.

Current process:
1. Add all common features to the dev branch
8. Merge those changes to the main branch
9. Merge those to each of the jurisdiction branches (at the moment it is three)
10. Make any adjustments needed for each jurisdiction such as different translations
11. Release each jurisdictions

New Process:
1. Add all common features to the dev branch. Also add any jurisdiction divergences as well in the appropriate jurisdiction override directory
6. Merge those to the main branch
7. Release each jurisdiction

## How Can This Be Tested/Reviewed?

**Note:** in order to have this working locally and to test the different jurisdictions you will need to update the `.env` file for the public site to have a proper jurisdiction. `JURISDICTION_NAME=San Jose`, `JURISDICTION_NAME=Alameda`, or `JURISDICTION_NAME=San Mateo`  

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have added QA notes to the issue with applicable URLs
- [ ] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] I have exported any new pieces added to ui-components
- [ ] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue, and ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

### CODE REVIEW

**Review by ColinBuyck — COMMENTED** [review]
I'm noticing a difference in the homepage icons between this PR and the respective dev branches.

image
Screen Shot 2022-10-26 at 10 51 17 AM

**Review by ColinBuyck — APPROVED** [review]
Everything else LGTM once that homepage button issue is resolved 🍾

**Review by emilyjablonski — CHANGES_REQUESTED** [review]
Noticed a few discrepancies from production sites:
* We've lost the numbering of sections on the privacy policy page
* San Mateo is missing the right hand panel contact section on the get assistance page
* The MD pages are loading pretty slowly for me locally and in somewhat of an awkward empty state, I'd love to add some sort of loading state to these pages, wdyt?

Very excited about this!

**Comment by ludtkemorgan** [comment]
> Noticed a few discrepancies from production sites:
> 
> * We've lost the numbering of sections on the privacy policy page
> * San Mateo is missing the right hand panel contact section on the get assistance page
> * The MD pages are loading pretty slowly for me locally and in somewhat of an awkward empty state, I'd love to add some sort of loading state to these pages, wdyt?
> 
> Very excited about this!

Thanks @emilyjablonski . Nice catches. I've fixed the numbering section and the contact section in San Mateo. For the loading state I tried to put the `LoadingOverlay` component over the places that that happened. However it didn't really seem any better because the page still jumped when it loaded. And another thing that I ran into is after the first load it was really fast. I could be wrong, but I think that slow load will only happen to the first user to hit that page in production after every release. Thoughts?

**Review by emilyjablonski — APPROVED** [review]
All good that makes sense to me, thanks!

**Pull request merged**
