### PR TITLE
modify whatToExpect language for Reilly Station

### PR DESCRIPTION
**Pull request by bk3c**
Add the word "lottery" for the Reilly Station listing, per Eden request.

@slowbot, @vubang228: Is this spot enough, or do we need to alter the other two sentences as well?

### CODE REVIEW

**Comment by vubang228** [comment]
@bk3c Where can I see the spot "lottery" was placed, I didn't see it on the staging site?

**Comment by bk3c** [comment]
@vubang228:

image

**Comment by bk3c** [comment]
I'm going to go ahead and merge this so they can easily see it on staging and do final QA if we want to launch it on Monday.

**Comment by vubang228** [comment]
@bk3c Just sent to them to QA. I just noticed the Household Maximum Income wasn't updated with the chart that's in the spreadsheet, I boldfaced the numbers that need to be updated. Here are the ones that are incorrect in the listing. Will let you know what what their QA response is, hoping we're still ok for 10AM Monday launch. 

Screen Shot 2020-08-01 at 8 15 47 AM

**Comment by vubang228** [comment]
Eden housing just checked in and only the changes to these two dollar amounts need to change. We are all good for 10am tomorrow (Monday)! @Bk3c

**Pull request merged**
