### PR TITLE
Add Eastlake listing

### PR DESCRIPTION
**Pull request by software-project**
Adds Eastlake listing for Alameda #66

### CODE REVIEW

**Comment by software-project** [comment]
@vubang228 It's a work in progress as not all data is filled on the spreadsheet.

**Comment by vubang228** [comment]
@software-project I think we have enough of what we need to do a first draft? From my understanding, our process will be getting at least 70% of the spreadsheet filled out to show the partner a site, and we'll be working on the remaining 30% when they see the draft.

**Comment by software-project** [comment]
@vubang228 yeah, I think we are at least 70% ready, so @bk3c can merge it if he feels like it's fine

**Comment by bk3c** [comment]
@jaredcwhite Can you weigh in on overriding the ui-components here? This otherwise LGTM, and I'm fine with just doing it locally in the short term (or even long-term if we decide that's better), but I just want to make sure you and @software-project are coordinated on a vision.

**Comment by software-project** [comment]
@jaredcwhite @bk3c I will update bloom housing then

**Comment by bk3c** [comment]
@software-project Ok, the big merge is done, so feel free to adjust and rebase this as necessary and then I should be able to review and merge it quickly.

**Comment by software-project** [comment]
@bk3c thanks

**Comment by vubang228** [comment]
@bk3c is this ready for QA then?

**Comment by software-project** [comment]
@bk3c I fixed the address. Regarding closed listings, I was fixed it, so it should be working fine. At least it's working for me locally with `yarn dev:ala`

**Comment by bk3c** [comment]
@software-project It still looks wrong for me on the home page with the latest from this branch:

image

**Comment by vubang228** [comment]
I wanted to check in on this @bk3c @software-project, now that our current pilot opportunity fell through, this might be the next one up. I'd like to get this listing up before reaching out to them for a digital app pilot though. Thanks!

**Comment by bk3c** [comment]
Ok, I'm going to merge this so QA is easier on staging, and then file a separate issue for the home page thing.

**Pull request merged**
